### ISSUE TITLE
Questions about floorplan.txt

### ISSUE THREAD

**Issue by Arnoldnuo** [art-programmer/FloorNet#13]
How is the floorplan.txt file obtained?
1. If it is manual labeling, is there a labeling tool? I did not see the generated code for floorplan.txt in the FloorplanAnnotator.
2. Which image is floorplan.txt based on? Is it based on the density map image of the 3D model?

floorplan.txt文件是怎么获取的呢？
1. 如果是人工标注的话，是否有标注工具呢？我在FloorplanAnnotator中并没有看到floorplan.txt的生成代码。
2. floorplan.txt是基于哪张图做的标注呢？是基于3D模型的密度图来做的标记吗？

**Comment by art-programmer** [comment]
Yes, we have an annotator to label data (annotating floorplan.txt) based on the density map of the 3D model. However, the annotator is written in Lua and not well-organized (hard for others to compile and customize). So we shared the FloorplanAnnotator which is written in Python for a similar task. So you need to modify it slightly. To be specific, you can change the save function [here](https://github.com/art-programmer/FloorplanAnnotator/blob/bc828c9823591ab8fe30ef153657277d9cfbb571/libs/scene.py#L196-L200) to export floorplan.txt. The format of floorplan.txt is explained [here](https://github.com/art-programmer/FloorplanTransformation).
