### ISSUE TITLE
I want to get reconstructFloorplan pred data,  but when i debug code , the floornetplan (result_pred) is {}

### ISSUE THREAD

**Issue by Leibosite** [art-programmer/FloorNet#14]
when I run "python train.py --task=evaluate" to get result_gred , but it always is {}.    at  evaluate.py  320 line. 
data from https://drive.google.com/drive/folders/16lyX_xTiALUzKyst86WJHlhpTDr8XPF_

**Comment by KoykL** [comment]
Could you try 
```
python train.py --task=evaluate --separateIconLoss
```
Thanks!

**Comment by Leibosite** [comment]
ok , thanks!
