### ISSUE TITLE
evaluate.py not run

### ISSUE THREAD

**Issue by 823639792** [art-programmer/FloorNet#2]
我首先执行：
python train.py --batchSize=3
之后执行:
python evaluate.py 
然而脚本并不能直接执行，所以我修改了执行的指令 
python train.py --task=evaluate --separateIconLoss
不知道这样做对吗？

**Comment by chenliu-wustl** [comment]
嗯嗯，我们的README写错了，应该是python train.py --task=evaluate，多谢提醒！
