### ISSUE TITLE
Disable Gurobi

### ISSUE THREAD

**Issue by 823639792** [art-programmer/FloorNet#5]
有什么简单方法不使用Gurobi吗？
因为我已经毕业了，无法申请到免费的授权，Gurobi的的授权对我来说实在有些贵～
如果不使用Gurobi对结果影响大吗，还是只影响运算时间?

**Comment by art-programmer** [comment]
不使用Gurobi的话只能得到中间结果（墙角），无法得到连线。可以考虑用一些Heuristics来确定连线，但是不确定效果怎么样。
